const bill = {
    name : '真实姓名',
    identityNo : '身份证号',
    identityPhoto : '身份证照片',
    staff : '职务',
    source : '来源',
    province : '所在地区',
    street : '街道地址',
    tel : '联系电话',
    email : '电子邮件',
    fax : '传真',
    enterpriseName : '企业全称',
    shortName : '企业简称',
    website : '企业官网',
    creditCode : '统一社会信用代码',
    creditPhoto : '营业执照扫描件',
    companyDescription : '企业描述',
    annualTurnover : '年营业额',
    team : '软件研发团队',
    starProduct : '以往明星产品',
    productName : '产品名称',
    productType : '产品类型',
    linkType : '联网方式',
    operateSystem : '操作系统',
    productDescription : '产品描述',
    companyFile : '企业资料',
    starFile : '明星产品资料',
    productFile : '拟接入产品料'
}
export {bill}